better_than_ever/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from store import views as store_views
from raffles import views as raffle_views
from django.contrib.auth import views as auth_views

# Registration and login currently broken 03-01-20

urlpatterns = [
    path('admin/', admin.site.urls),
    path('leaderboard/', user_views.LeaderBoardView.as_view(), name='leaderboard'),
    path('weightupdate/', user_views.WeightUpdateView.as_view(), name='weightupdate'),
    path('profileupdate/', user_views.UpdateProfileView.as_view(), name='profileupdate'),
    path('signup/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/register.html'), name='login'),
    path('challenge/', user_views.landing, name='fitness_challenge'),
    path('store/', store_views.store, name='store'),
    path('', store_views.landing, name='landing'),
    path('pricing/', store_views.pricing, name='pricing'),
    path('home/', store_views.Home.as_view(), name='home'),
    path('workouts/', include('workouts.urls')),
    path('recipes/', include('recipes.urls')),
    path('generalhealth/', include('general_health.urls')),
    path('raffles/', include('raffles.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Test users have their password in the form Password!{Number}

raffles/urls.py
from django.urls import path
from .views import (
    entry,
    register,
)

urlpatterns = [
    path('', entry, name='entry'),
    path('register', register, name='raffle-register'),
]

workouts/urls.py
from django.urls import path
from .views import (
    cardio,
    general,
    flexibility,
    meditation,
    speed,
    strength,
    catalog,
)

urlpatterns = [
    path('general', general, name='workouts-general'),
    path('cardio', cardio, name='workouts-cardio'),
    path('flexibility', flexibility, name='workouts-flexibility'),
    path('meditation', meditation, name='workouts-meditation'),
    path('speed', speed, name='workouts-speed'),
    path('strength', strength, name='workouts-strength'),
    path('', catalog, name='workouts-catalog'),
]

better_than_ever/workouts/models.py
from django.db import models

class Workout(models.Model):
    title = models.CharField(max_length=140)
    description = models.CharField(max_length=300)
    link = models.CharField(max_length=500)
    duration = models.CharField(max_length=50)


    CATEGORY_CHOICES = [
        ('CA', 'Cardio'),
        ('ST', 'Strength'),
        ('EN', 'Endurance'),
        ('FL', 'Flexibility'),
        ('ME', 'Meditation'),
        ('SP', 'Speed')
    ]
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES)

    def __str__(self):
        return f'{self.title}'

workouts/models.py
from django.db import models

class Workout(models.Model):
    title = models.CharField(max_length=140)
    description = models.CharField(max_length=300)
    link = models.CharField(max_length=500)
    INTENSITY_CHOICES= [
        ('L', 'Low'),
        ('M', 'Medium'),
        ('H', 'High')
    ]
    intensity = models.CharField(max_length=1, choices=INTENSITY_CHOICES)
    CATEGORY_CHOICES = [
        ('CA', 'Cardio'),
        ('ST', 'Strength'),
        ('FL', 'Flexibility'),
        ('ME', 'Meditation'),
        ('SP', 'Speed'),
        ('GE', 'General')
    ]
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES)

    def __str__(self):
        return f'{self.title}'

workouts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .models import Workout
# #
def general(request, *args, **kwargs):
    if request.method == 'GET':
        context = {
            'workouts': Workout.objects.filter(category='GE')
        }
        return render(request, 'workouts/general.html', context)

def cardio(request, *args, **kwargs):
    if request.method == 'GET':
        context = {
            'workouts': Workout.objects.filter(category='CA')
        }
        return render(request, 'workouts/cardio.html', context)

def strength(request, *args, **kwargs):
    if request.method == 'GET':
        context = {
            'workouts': Workout.objects.filter(category='ST')
        }
        return render(request, 'workouts/strength.html', context)

def flexibility(request, *args, **kwargs):
    if request.method == 'GET':
        context = {
            'workouts': Workout.objects.filter(category='FL')
        }
        return render(request, 'workouts/flexibility.html', context)

def meditation(request, *args, **kwargs):
    if request.method == 'GET':
        context = {
            'workouts': Workout.objects.filter(category='ME')
        }
        return render(request, 'workouts/meditation.html', context)

def speed(request, *args, **kwargs):
    if request.method == 'GET':
        context = {
            'workouts': Workout.objects.filter(category='SP')
        }
        return render(request, 'workouts/speed.html', context)

def catalog(request, *args, **kwargs):
    return render(request, template_name='workouts/catalog.html')

workouts/templates/workouts/cardio.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Cardio + Endurance Training Workout Videos Page</title>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.2/css/bootstrap.min.css'>
  <link rel="stylesheet" href="{% static 'workouts/cardio.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              </ul>
            </div>
          </div>
        </div>
      </div>

          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Cardio + Endurance Training Workouts</h1>
          <br>
          <p class="lead text">Our cardio and endurance training videos will strengthen your respiratory and cardiovascular systems trhough low intensity but long and strenuous exercises, developing lean muscle and drastically improve your fitness without too much of a change in size and weight.
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
<br>
          <br>
          <div class="row">
            {% for workout in workouts %}
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                  <h4 class="card-text">{{ workout.title }}</h4>
                  <br>
  <iframe id="ytplayer" type="text/html" width="348" height="250"
    src="https://www.youtube.com/embed/{{ workout.link }}"
    frameborder="0"></iframe>
                  <div class="card-body">
                    <p class="card-text">{{ workout.description }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <button type="button" class="btn btn-danger btn-sm">Like</button>
                        
                        <button type="button" class="btn btn-primary btn-sm">Share</button>
                      </div>
                      <small class="text-muted">Intensity: {{ workout.get_intensity_display }}</small>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}

          </div>
        </div>
      </div>

    </main>
    </footer>
<br>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- partial -->
  <script  src="{% static 'workouts/cardio.js' %}"></script>

</body>
</html>

workouts/templates/workouts/flexibility.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Flexibility Training Workout Videos Page</title>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.2/css/bootstrap.min.css'>
  <link rel="stylesheet" href="{% static 'workouts/cardio.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              </ul>
            </div>
          </div>
        </div>
      </div>

          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Flexibility Exercises</h1>
          <br>
          <p class="lead text">Our flexibilty training videos will expand your range of movement  through both stationary and dynamic stretching exercises, loosening up your muscles and improving all areas of your mobility, even making you more resilient to physical injury that often result from overstretched and overused muscles.
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
<br>
          <br>
          <div class="row">
            {% for workout in workouts %}
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                  <h4 class="card-text">{{ workout.title }}</h4>
                  <br>
  <iframe id="ytplayer" type="text/html" width="348" height="250"
    src="https://www.youtube.com/embed/{{ workout.link }}"
    frameborder="0"></iframe>
                  <div class="card-body">
                    <p class="card-text">{{ workout.description }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <button type="button" class="btn btn-danger btn-sm">Like</button>
                        
                        <button type="button" class="btn btn-primary btn-sm">Share</button>
                      </div>
                      <small class="text-muted">Intensity: {{ workout.get_intensity_display }}</small>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
        </div>
      </div>
    </div>

    </main>
    </footer>
<br>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- partial -->
  <script  src="{% static 'workouts/cardio.js' %}"></script>

</body>
</html>

workouts/templates/workouts/general.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - General Health + Fitness Workout Videos Page</title>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.2/css/bootstrap.min.css'>
  <link rel="stylesheet" href="{% static 'workouts/cardio.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              </ul>
            </div>
          </div>
        </div>
      </div>

          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">General Health + Fitness Workouts</h1>
          <br>
          <p class="lead text">Description from catalog for general health + fitness workouts
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
<br>
          <br>
          <div class="row">
            {% for workout in workouts %}
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                  <h4 class="card-text">{{ workout.title }}</h4>
                  <br>
  <iframe id="ytplayer" type="text/html" width="348" height="250"
    src="https://www.youtube.com/embed/{{ workout.link }}"
    frameborder="0"></iframe>
                  <div class="card-body">
                    <p class="card-text">{{ workout.description }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <button type="button" class="btn btn-danger btn-sm">Like</button>
                        
                        <button type="button" class="btn btn-primary btn-sm">Share</button>
                      </div>
                      <small class="text-muted">Intensity: {{ workout.get_intensity_display }}</small>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>

    </main>
    </footer>
<br>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- partial -->
  <script  src="{% static 'workouts/cardio.js' %}"></script>

</body>
</html>

workouts/templates/workouts/meditation.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Meditation + Yoga Videos Page</title>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.2/css/bootstrap.min.css'>
  <link rel="stylesheet" href="{% static 'workouts/cardio.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              </ul>
            </div>
          </div>
        </div>
      </div>

          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Meditation + Yoga Exercises</h1>
          <br>
          <p class="lead text">Our medidtation and yoga exercise videos will provide numerous beenfits toboth your body and mind, using a relaxed and peaceful environment to gradually improve your balance, endurance, and flexibility, while also keeping your mind healthy by relieving stress and anxiety, allowing for a tranquil and therapeutic method of taking your level of physical and mental fitness to a new level.
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
<br>
          <br>
          <div class="row">
            {% for workout in workouts %}
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                  <h4 class="card-text">{{ workout.title }}</h4>
                  <br>
  <iframe id="ytplayer" type="text/html" width="348" height="250"
    src="https://www.youtube.com/embed/{{ workout.link }}"
    frameborder="0"></iframe>
                  <div class="card-body">
                    <p class="card-text">{{ workout.description }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <button type="button" class="btn btn-danger btn-sm">Like</button>
                        
                        <button type="button" class="btn btn-primary btn-sm">Share</button>
                      </div>
                      <small class="text-muted">Intensity: {{ workout.get_intensity_display }}</small>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
              
          </div>
        </div>
      </div>

    </main>
    </footer>
<br>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- partial -->
  <script  src="{% static 'workouts/cardio.js' %}"></script>

</body>
</html>

workouts/templates/workouts/speed.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Speed + Agility Training Workout Videos Page</title>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.2/css/bootstrap.min.css'>
  <link rel="stylesheet" href="{% static 'workouts/cardio.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              </ul>
            </div>
          </div>
        </div>
      </div>

          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Speed + Agility Training Workouts</h1>
          <br>
          <p class="lead text">Our speed and agility training videos will improve your mobility and allow you to not only get faster but maintain your top speed for longer to perfect aceration and movement, untilizing high-intensity interval traing including many differenttypes of spritning drills, allowing you toachieve your most mobile, quick self.
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
<br>
          <br>
          <div class="row">
            {% for workout in workouts %}
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                  <h4 class="card-text">{{ workout.title }}</h4>
                  <br>
  <iframe id="ytplayer" type="text/html" width="348" height="250"
    src="https://www.youtube.com/embed/{{ workout.link }}"
    frameborder="0"></iframe>
                  <div class="card-body">
                    <p class="card-text">{{ workout.description }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <button type="button" class="btn btn-danger btn-sm">Like</button>
                        
                        <button type="button" class="btn btn-primary btn-sm">Share</button>
                      </div>
                      <small class="text-muted">Intensity: {{ workout.get_intensity_display }}</small>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>

    </main>
    </footer>
<br>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- partial -->
  <script  src="{% static 'workouts/cardio.js' %}"></script>

</body>
</html>

workouts/templates/workouts/strength.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Strength Training Workout Videos Page</title>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.2/css/bootstrap.min.css'>
  <link rel="stylesheet" href="{% static 'workouts/cardio.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              </ul>
            </div>
          </div>
        </div>
      </div>

          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Strength Training Workouts</h1>
          <br>
          <p class="lead text">Our strength training videos will provide high intensity exercise for large muscle groups and develop them them to make your body bigger and stronger with increased muscle mass.
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
<br>
          <br>
          <div class="row">
            {% for workout in workouts %}
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                  <h4 class="card-text">{{ workout.title }}</h4>
                  <br>
  <iframe id="ytplayer" type="text/html" width="348" height="250"
    src="https://www.youtube.com/embed/{{ workout.link }}"
    frameborder="0"></iframe>
                  <div class="card-body">
                    <p class="card-text">{{ workout.description }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <button type="button" class="btn btn-danger btn-sm">Like</button>
                        
                        <button type="button" class="btn btn-primary btn-sm">Share</button>
                      </div>
                      <small class="text-muted">Intensity: {{ workout.get_intensity_display }}</small>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>

    </main>
    </footer>
<br>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- partial -->
  <script  src="{% static 'workouts/cardio.js' %}"></script>

</body>
</html>